name: Build the android app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      
      - name: Check files
        run: tree app/build/outputs/apk

      - name: Upload to github artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: customfetch-android-app
          path: app/build/outputs/apk/debug/app-debug.apk
